local _G				= GLOBAL
local require			= GLOBAL.require
local TUNING			= GLOBAL.TUNING

--TUNING.TODO = 0


TUNING.STPATRICK_GNOME_LUCK				= 0.1
TUNING.STPATRICK_GNOME_HELD_BONUS		= 0.15
TUNING.STPATRICK_GNOME_STACK_BONUS		= 0.02
